### ISSUE TITLE
ERR! notarget 0.0.1-security

### ISSUE THREAD

**Issue by haneyman** [mikaoelitiana/cordova-plugin-ios-no-export-compliance#5]
Hello, thanks for this great plugin.  I am receiving an error during "ionic platform add ios" which essentially calls cordova's platform add:
notarget Valid install targets:
npm ERR! notarget 0.0.1-security
npm ERR! notarget 

Any idea what is causing this?

**Comment by mikaoelitiana** [comment]
Hello @haneyman, thank for reporting this issue. I will try to investigate this.

**Comment by mikaoelitiana** [comment]
I think this is not an issue related to the cordova-plugin-ios-no-export-compliance plugin. You may check https://github.com/npm/npm/issues/13743 that seems related to what you experienced.
