### ISSUE TITLE
Strange additional key "UIBackgroundModes"

### ISSUE THREAD

**Issue by braedwurscht** [mikaoelitiana/cordova-plugin-ios-no-export-compliance#9]
Thanks a lot for the great plugin, but why is there a second *-Info.plist key which sets a "Required background mode" to `remote-notification` as explained [here](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW22)? 

In my opinion this doesn't belong to this plugin and is nowhere explained. So either the plugin name is misleading or this shouldn't be included.

**Comment by mikaoelitiana** [comment]
You are right, I should remove that.

**Comment by mikaoelitiana** [comment]
Thank you @braedwurscht, this has been fixed now.

**Comment by braedwurscht** [comment]
Awesome, that was fast. Thank you very much @mikaoelitiana.

**Comment by braedwurscht** [comment]
There is only one thing I noticed. Upon removing the key "UIBackgroundModes" the cli states that the plugin has been installed for android and for ios. Whereas before it just said installing for ios?

**Comment by mikaoelitiana** [comment]
I think it is because there is no change made on the android side and it is ignored. I can check anyway if this created an issue.

**Comment by braedwurscht** [comment]
It doesn't seem to create any issues or side effects on android. At least at the first glance, I still can build and run my app without any problems. But thanks anyway.
